### ISSUE TITLE
Create basic ("client version") variation

### ISSUE THREAD

**Issue by blanchardjeremy** [blanchardjeremy/arena-react#1]
May need to give a new URL mapping.

**Comment by blanchardjeremy** [comment]
@justinhaaheim I'd love your support to see the best way to refactor things so that there is a basic version of the arena available. Is it through routing? Or just making `client.html` call the same React App script? And if so, then how do we re-use all the HTML in `index.html`?

**Comment by justinhaaheim** [comment]
Routing could work. We could also set this up to build three different
versions of the arena.

The easiest approach would be to just depend on a URL parameter. That's
easy to check from js without changes to the server.

**Comment by blanchardjeremy** [comment]
Yeah. That was my first thought too. 

It's a little harder to make it easy for coaches to send to their clients, though. 

Ideally, I think it would be https://setthearena.com/basic (or /client)

If we don't go the URL param approach, what's entailed in creating a new basic`/index.html` file that imports the main `index.html` file with a variable to switch modes?

**Comment by justinhaaheim** [comment]
Siteground can do redirects, right? If so it shouldn't be hard to take
everyone going to /client.html right now and redirect them to /?type=client

Not exactly sure what you're asking about "a new basic index.html". Is this
the scenario where we build to index.html, client.html and swedish.html and
then hardcode a prop for which language to use in the html/JS? I don't know
exactly what's required there, but it would likely mean creating a custom
webpack config.

The only thing with using a full url like `/basic` is that we would need to
update the server so that it serves index.html for *all routes*. Do you
know how to do that?
