### ISSUE TITLE
Request: Return to two columns

### ISSUE THREAD

**Issue by blanchardjeremy** [blanchardjeremy/arena-react#11]
Zach and Michele said they both prefer the columns.

I don't agree. But I wanted to jot it down here for conversation.

**Comment by blanchardjeremy** [comment]
I heard from two housemates that they prefer the columns as well.

**Comment by blanchardjeremy** [comment]
@justinhaaheim Curious your thoughts. What prompted the switch to the "word cloud"?

**Comment by justinhaaheim** [comment]
Re: the row design: It's a better use of the space, a more common design pattern and better adapts to different screen sizes. 

I hear the comments from the housemates + Zach + Michelle. A couple things about that:

You always have to be careful with negative feedback because your dataset is inherently biased: people who dislike a thing are much more likely to complain vocally than people who like the thing. And people who like the thing might not even be fully conscious of the fact that they like it. 

It's tempting to cater to the negative feedback, but my suggestion in general is take the negative feedback, but keep it in perspective, and cater to what is a good, accessible user experience that matches the vision.

**Comment by justinhaaheim** [comment]
Also re: design changes: there's also the "bring back the old Facebook!" effect. People (myself included) veeeery often tend to dislike UI changes. My hunch is it's rooted in human's general dislike of change when you're comfortable with something. People hate the new Reddit design. People have hated many iterations of Twitter and FB redesigns. I bet if there's ever a Gmail redesign people will hate it. But that doesn't mean it's bad. Wait two years and then force people back onto the old design and I bet people would revolt. 🙂

All of this is to say: I think we should be bold, align to good UI design patterns and accessibility patterns, and stick with the rows unless there's a demonstrably better design.

**Comment by justinhaaheim** [comment]
![694D36B9-E64A-4C84-9943-FF14C33254C6](https://user-images.githubusercontent.com/3389743/94875409-a1c21500-0409-11eb-856c-458451b1bc97.jpeg)
Example of a UI that allows the user to easily select from a collection of 10+ items

**Comment by blanchardjeremy** [comment]
Good points. What UI library is that from?

**Comment by blanchardjeremy** [comment]
Molly gave input that button spacing did the trick. Resolved with latest version.
